const products = [
    {
      id: 1,
      name: 'Ring',
      price: '$200',
      image: '/photos/Strawberries/Types/Type1.jpg',
    },
    {
      id: 2,
      name: 'Watch',
      price: '$300',
      image: '/photos/Strawberries/Types/Type2.jpg',
    },
    {
      id: 3,
      name: 'Teddy Bear',
      price: '$110',
      image: '/photos/Strawberries/Types/Type3.jpg',
    },
    {
      id: 4,
      name: 'Flower Bouquet',
      price: '$45',
      image: '/photos/Strawberries/Types/Type4.jpg',
    },
    {
      id: 5,
      name: 'Teddy Bear',
      price: '$95',
      image: '/photos/Strawberries/Types/Type5.jpg',
    },
    {
      id: 6,
      name: 'Flower Bouquet',
      price: '$70',
      image: '/photos/Strawberries/Types/Type6.jpg',
    },
    {
        id: 7,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Types/Type6.jpg',
      },
      {
        id: 8,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Types/Type6.jpg',
      },
      {
        id: 9,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Types/Type6.jpg',
      },
      {
        id: 10,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Types/Type6.jpg',
      },
      {
        id: 11,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Types/Type6.jpg',
      },
      {
        id: 12,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Types/Type6.jpg',
      },
      {
        id: 13,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Types/Type6.jpg',
      },
      {
        id: 14,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Types/Type6.jpg',
      },
      {
        id: 15,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Types/Type6.jpg',
      },
      {
        id: 16,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Types/Type6.jpg',
      },
      {
        id: 17,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Types/Type6.jpg',
      },
      {
        id: 18,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Types/Type6.jpg',
      },
      {
        id: 19,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Types/Type6.jpg',
      },
      {
        id: 20,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Types/Type6.jpg',
      },
      {
        id: 6,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Types/Type6.jpg',
      },
      {
        id: 6,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Types/Type6.jpg',
      },
      {
        id: 6,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Types/Type6.jpg',
      },
      {
        id: 6,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Types/Type6.jpg',
      },
      {
        id: 6,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Types/Type6.jpg',
      },
      {
        id: 6,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Types/Type6.jpg',
      },
                                            
  ];

export default products;