const products = [
    {
      id: 1,
      name: 'Ring',
      price: '$200',
      image: '/photos/Strawberries/Types/Type1.jpg',
    },
    {
      id: 2,
      name: 'Watch',
      price: '$300',
      image: '/photos/Strawberries/Types/Type2.jpg',
    },
    {
      id: 3,
      name: 'Teddy Bear',
      price: '$110',
      image: '/photos/Strawberries/Types/Type3.jpg',
    },
    {
      id: 4,
      name: 'Flower Bouquet',
      price: '$45',
      image: '/photos/Strawberries/Types/Type4.jpg',
    },
    {
      id: 5,
      name: 'Teddy Bear',
      price: '$95',
      image: '/photos/Strawberries/Types/Type5.jpg',
    },
    {
      id: 6,
      name: 'Flower Bouquet',
      price: '$70',
      image: '/photos/Strawberries/Types/Type6.jpg',
    },
    {
        id: 7,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Boxes/Box1.jpg',
      },
      {
        id: 8,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Boxes/Box2.jpg',
      },
      {
        id: 9,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Boxes/Box3.jpg',
      },
      {
        id: 10,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Boxes/Box4.jpg',
      },
      {
        id: 11,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Boxes/Box5.jpg',
      },
      {
        id: 12,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Boxes/Box6.jpg',
      },
      {
        id: 13,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Boxes/Box7.jpg',
      },
      {
        id: 14,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Boxes/Box8.jpg',
      },
      {
        id: 15,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Boxes/Box9.jpg',
      },
      {
        id: 16,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Boxes/Box10.jpg',
      },
      {
        id: 17,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Boxes/Box11.jpg',
      },
      {
        id: 18,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Boxes/Box12.jpg',
      },
      {
        id: 19,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Boxes/Box13.jpg',
      },
      {
        id: 20,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Boxes/Box14.jpg',
      },
      {
        id: 21,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Boxes/Box15.jpg',
      },
      {
        id: 22,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Boxes/Box16.jpg',
      },
      {
        id: 23,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Boxes/Box17.jpg',
      },
      {
        id: 24,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Boxes/Box18.jpg',
      },
      {
        id: 25,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Boxes/Box19.jpg',
      },
      {
        id: 26,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Boxes/Box20.jpg',
      },
      {
        id: 27,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Boxes/Box21.jpg',
      },
      {
        id: 28,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Boxes/Box22.jpg',
      },
      {
        id: 29,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Strawberries/Bouquet/Bouquet1.jpg',
      },
      {
        id: 30,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Eclairs/Eclairs1.jpg',
      }, 
      {
        id: 31,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Chocolates/Chocolate1.jpg',
      },
      {
        id: 32,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Chocolates/Chocolate2.jpg',
      },
      {
        id: 33,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Chocolates/Chocolate3.jpg',
      },
      {
        id: 34,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Chocolates/Chocolate4.jpg',
      },
      {
        id: 35,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Chocolates/Chocolate5.jpg',
      }, 
      {
        id: 36,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Candy/Candy1.jpg',
      },
      {
        id: 37,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Candy/Candy2.jpg',
      },
      {
        id: 38,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Candy/Candy3.jpg',
      },
      {
        id: 39,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Candy/Candy4.jpg',
      },
      {
        id: 40,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Candy/Candy5.jpg',
      },
      {
        id: 41,
        name: 'Flower Bouquet',
        price: '$70',
        image: '/photos/Candy/Candy6.jpg',
      },                                   
  ];

export default products;