const products = [
    {
      id: 1,
      name: 'Strawberries',
      type: 'strawberries',
      price: '$10',
      image: '/photos/Strawberries/Types/Type1.jpg',
    },
    {
      id: 2,
      name: 'Strawberries',
      type: 'strawberries',
      price: '$13.50',
      image: '/photos/Strawberries/Types/Type2.jpg',
    },
    {
      id: 3,
      name: 'Strawberries',
      type: 'strawberries',
      price: '$14',
      image: '/photos/Strawberries/Types/Type3.jpg',
    },
    {
      id: 4,
      name: 'Strawberries',
      type: 'strawberries',
      price: '$12',
      image: '/photos/Strawberries/Types/Type4.jpg',
    },
    {
      id: 5,
      name: 'Strawberries',
      type: 'strawberries',
      price: '$8',
      image: '/photos/Strawberries/Types/Type5.jpg',
    },
    {
      id: 6,
      name: 'Strawberries',
      type: 'strawberries',
      price: '$15',
      image: '/photos/Strawberries/Types/Type6.jpg',
    },
    {
        id: 7,
        name: 'Strawberries Boxes',
        type: 'strawberries',
        price: '$13.50',
        image: '/photos/Strawberries/Boxes/Box1.jpg',
      },
      {
        id: 8,
        name: 'Strawberries Boxes',
        type: 'strawberries',
        price: '$12',
        image: '/photos/Strawberries/Boxes/Box2.jpg',
      },
      {
        id: 9,
        name: 'Strawberries Boxes',
        type: 'strawberries',
        price: '$12',
        image: '/photos/Strawberries/Boxes/Box3.jpg',
      },
      {
        id: 10,
        name: 'Strawberries Boxes',
        type: 'strawberries',
        price: '$12',
        image: '/photos/Strawberries/Boxes/Box4.jpg',
      },
      {
        id: 11,
        name: 'Strawberries Boxes',
        type: 'strawberries',
        price: '$12',
        image: '/photos/Strawberries/Boxes/Box5.jpg',
      },
      {
        id: 12,
        name: 'Strawberries Boxes',
        type: 'strawberries',
        price: '$14',
        image: '/photos/Strawberries/Boxes/Box6.jpg',
      },
      {
        id: 13,
        name: 'Strawberries Boxes',
        type: 'strawberries',
        price: '$24',
        image: '/photos/Strawberries/Boxes/Box7.jpg',
      },
      {
        id: 14,
        name: 'Strawberries Boxes',
        type: 'strawberries',
        price: '$12',
        image: '/photos/Strawberries/Boxes/Box8.jpg',
      },
      {
        id: 15,
        name: 'Strawberries Boxes',
        type: 'strawberries',
        price: '$16',
        image: '/photos/Strawberries/Boxes/Box9.jpg',
      },
      {
        id: 16,
        name: 'Strawberries Boxes',
        type: 'strawberries',
        price: '$16',
        image: '/photos/Strawberries/Boxes/Box10.jpg',
      },
      {
        id: 17,
        name: 'Strawberries Boxes',
        type: 'strawberries',
        price: '$22',
        image: '/photos/Strawberries/Boxes/Box11.jpg',
      },
      {
        id: 18,
        name: 'Strawberries Boxes',
        type: 'strawberries',
        price: '$26',
        image: '/photos/Strawberries/Boxes/Box12.jpg',
      },
      {
        id: 19,
        name: 'Strawberries Boxes',
        type: 'strawberries',
        price: '$24.50',
        image: '/photos/Strawberries/Boxes/Box13.jpg',
      },
      {
        id: 20,
        name: 'Strawberries Boxes',
        type: 'strawberries',
        price: '$15',
        image: '/photos/Strawberries/Boxes/Box14.jpg',
      },
      {
        id: 21,
        name: 'Strawberries Boxes',
        type: 'strawberries',
        price: '$18',
        image: '/photos/Strawberries/Boxes/Box15.jpg',
      },
      {
        id: 22,
        name: 'Strawberries Boxes',
        type: 'strawberries',
        price: '$28',
        image: '/photos/Strawberries/Boxes/Box16.jpg',
      },
      {
        id: 23,
        name: 'Strawberries Boxes',
        type: 'strawberries',
        price: '$30',
        image: '/photos/Strawberries/Boxes/Box17.jpg',
      },
      {
        id: 24,
        name: 'Strawberries Boxes',
        type: 'strawberries',
        price: '$36',
        image: '/photos/Strawberries/Boxes/Box18.jpg',
      },
      {
        id: 25,
        name: 'Strawberries Boxes',
        type: 'strawberries',
        price: '$34',
        image: '/photos/Strawberries/Boxes/Box19.jpg',
      },
      {
        id: 26,
        name: 'Strawberries Boxes',
        type: 'strawberries',
        price: '$30',
        image: '/photos/Strawberries/Boxes/Box20.jpg',
      },
      {
        id: 27,
        name: 'Strawberries Boxes',
        type: 'strawberries',
        price: '$28',
        image: '/photos/Strawberries/Boxes/Box21.jpg',
      },
      {
        id: 28,
        name: 'Strawberries Boxes',
        type: 'strawberries',
        price: '$48',
        image: '/photos/Strawberries/Boxes/Box22.jpg',
      },
      {
        id: 29,
        name: 'Strawberries Bouquet',
        type: 'strawberries',
        price: '$70',
        image: '/photos/Strawberries/Bouquet/Bouquet1.jpg',
      },
      {
        id: 30,
        name: 'Eclairs',
        type: 'eclairs',
        price: '$5',
        image: '/photos/Eclairs/Eclairs1.jpg',
      }, 
      {
        id: 31,
        name: 'Chocolates',
        type: 'chocolates',
        price: '$12',
        image: '/photos/Chocolates/Chocolate1.jpg',
      },
      {
        id: 32,
        name: 'Chocolates',
        type: 'chocolates',
        price: '$10',
        image: '/photos/Chocolates/Chocolate2.jpg',
      },
      {
        id: 33,
        name: 'Chocolates',
        type: 'chocolates',
        price: '$8',
        image: '/photos/Chocolates/Chocolate3.jpg',
      },
      {
        id: 34,
        name: 'Chocolates',
        type: 'chocolates',
        price: '$18',
        image: '/photos/Chocolates/Chocolate4.jpg',
      },
      {
        id: 35,
        name: 'Chocolates',
        type: 'chocolates',
        price: '$18',
        image: '/photos/Chocolates/Chocolate5.jpg',
      }, 
      {
        id: 36,
        name: 'Candy',
        type: 'candy',
        price: '$30',
        image: '/photos/Candy/Candy1.jpg',
      },
      {
        id: 37,
        name: 'Candy',
        type: 'candy',
        price: '$36',
        image: '/photos/Candy/Candy2.jpg',
      },
      {
        id: 38,
        name: 'Candy',
        type: 'candy',
        price: '$25',
        image: '/photos/Candy/Candy3.jpg',
      },
      {
        id: 39,
        name: 'Candy',
        type: 'candy',
        price: '$36',
        image: '/photos/Candy/Candy4.jpg',
      },
      {
        id: 40,
        name: 'Candy',
        type: 'candy',
        price: '$32',
        image: '/photos/Candy/Candy5.jpg',
      },
      {
        id: 41,
        name: 'Candy',
        type: 'candy',
        price: '$36',
        image: '/photos/Candy/Candy6.jpg',
      },                                   
  ];

export default products;